In [1]:

import tensorflow as tf

## data 선언
x_data =[[1.],[2.],[3.],[4.]]
y_data =[[1.],[3.],[5.],[7.]]



In [6]:
## 평균 0, 분산 1의 파라미터의 정규분포로 부터 값을 가져옴.
# 학습을 통해 업데이트가 되어 변화되는 모델의 파라미터인 w,b를 의미한다.
W = tf.Variable(tf.random.normal((1,1), mean=0, stddev=1.0))
b = tf.Variable(tf.random.normal((1,1), mean=0, stddev=1.0))

In [12]:
for j in range(len(x_data)):
    ## data * weight 작성
    WX = tf.matmul([x_data[j]], W)

    ## bias add 작성
    y_hat = tf.add(WX, b)

    ## W와 b로 예측 하기
    print("y_data: , ",y_data[j], "prediction : ", y_hat)

y_data: ,  [1.0] prediction :  tf.Tensor([[1.1104552]], shape=(1, 1), dtype=float32)
y_data: ,  [3.0] prediction :  tf.Tensor([[2.231135]], shape=(1, 1), dtype=float32)
y_data: ,  [5.0] prediction :  tf.Tensor([[3.3518145]], shape=(1, 1), dtype=float32)
y_data: ,  [7.0] prediction :  tf.Tensor([[4.472494]], shape=(1, 1), dtype=float32)


In [11]:
x_data =[[1.],[2.],[3.],[4.]]
y_data =[[1.],[3.],[5.],[7.]]

print(x_data)
print(y_data)

[[1.0], [2.0], [3.0], [4.0]]
[[1.0], [3.0], [5.0], [7.0]]
