In [4]:

import tensorflow as tf
import numpy as np
## data 선언
x_data =[[1.],[2.],[3.],[4.]]
y_data =[[1.],[3.],[5.],[7.]]



In [5]:

## 평균 0, 분산 1의 파라미터의 정규분포로 부터 값을 가져옴.
# 학습을 통해 업데이트가 되어 변화되는 모델의 파라미터인 w,b를 의미한다.
W=tf.Variable(tf.random.normal((1,1),mean=0, stddev=1.0))
b=tf.Variable(tf.random.normal((1,1),mean=0, stddev=1.0))
lr=tf.constant(0.0001)
history = np.zeros([2000, 3], 'float32')

In [15]:

for i in range(2000):  ## 에폭
    total_error = 0

    for j in range(len(x_data)): ## 배치 1
        ## data * weight
        WX =tf.matmul([x_data[j]], W) 

        ## bias add
        y_hat = tf.add(WX, b)

        ## 정답인 Y와 출력값의 error 계산
        error = tf.subtract([y_data[j]], y_hat)  #ture + prediction

        ## 경사하강법으로 W와 b 업데이트.
        ## 도함수 구하기
        diff_W = tf.multiply([x_data[j]], error) # error * x의합
        diff_b = error

        ##  업데이트할 만큼 러닝레이트 곱
        diff_W = tf.multiply(lr, diff_W)
        diff_b = tf.multiply(lr, diff_b) # lr *error

        ## w, b 업데이트
        W = tf.add(W, diff_W) # w + delta w + lr * x * (error)
        b = tf.add(b, diff_b) # b + delta b + lr * (error)
        #######
        visual_error = tf.square(error)
        ## 토탈 에러.
        total_error = total_error + visual_error

    ## 모든 데이터에 따른 error 값
    print("epoch: ", i, "error : ", total_error/len(x_data))
    history[i,:] = [(total_error/len(x_data))[0], W[0], b[0]]

epoch:  0 error :  tf.Tensor([[0.13240677]], shape=(1, 1), dtype=float32)
epoch:  1 error :  tf.Tensor([[0.13239093]], shape=(1, 1), dtype=float32)
epoch:  2 error :  tf.Tensor([[0.13237502]], shape=(1, 1), dtype=float32)
epoch:  3 error :  tf.Tensor([[0.13235918]], shape=(1, 1), dtype=float32)
epoch:  4 error :  tf.Tensor([[0.13234337]], shape=(1, 1), dtype=float32)
epoch:  5 error :  tf.Tensor([[0.13232753]], shape=(1, 1), dtype=float32)
epoch:  6 error :  tf.Tensor([[0.13231172]], shape=(1, 1), dtype=float32)
epoch:  7 error :  tf.Tensor([[0.13229573]], shape=(1, 1), dtype=float32)
epoch:  8 error :  tf.Tensor([[0.13227992]], shape=(1, 1), dtype=float32)
epoch:  9 error :  tf.Tensor([[0.13226408]], shape=(1, 1), dtype=float32)
epoch:  10 error :  tf.Tensor([[0.13224828]], shape=(1, 1), dtype=float32)
epoch:  11 error :  tf.Tensor([[0.13223237]], shape=(1, 1), dtype=float32)
epoch:  12 error :  tf.Tensor([[0.13221656]], shape=(1, 1), dtype=float32)
epoch:  13 error :  tf.Tensor([[0.1

In [16]:

## 학습끝난 후 W와 b로 예측 하기
print("W : ", W)
print("b : ", b)
print("input 3 : ", tf.add(tf.multiply(3, W), b))
print("input 4 : ", tf.add(tf.multiply(4, W), b))

W :  tf.Tensor([[1.7315125]], shape=(1, 1), dtype=float32)
b :  tf.Tensor([[-0.21027979]], shape=(1, 1), dtype=float32)
input 3 :  tf.Tensor([[4.9842577]], shape=(1, 1), dtype=float32)
input 4 :  tf.Tensor([[6.7157702]], shape=(1, 1), dtype=float32)
