In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
fish = pd.read_csv('https://bit.ly/fish_csv_data')
fish.head()
fish["Species"].value_counts()

Perch        56
Bream        35
Roach        20
Pike         17
Smelt        14
Parkki       11
Whitefish     6
Name: Species, dtype: int64

In [3]:
fish_input = fish[['Weight','Length','Diagonal','Height','Width']].to_numpy()
fish_target = fish['Species'].to_numpy()

In [4]:
from sklearn.model_selection import train_test_split

train_input, test_input, train_target, test_target = train_test_split(
fish_input, fish_target)

In [5]:
from sklearn.preprocessing import StandardScaler

ss = StandardScaler()

ss.fit(train_input)
train_scaled = ss.transform(train_input)
test_scaled = ss.transform(test_input)

In [7]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()

lr.fit(train_scaled, train_target)

print(lr.score(train_scaled, train_target))
print(lr.score(test_scaled, test_target))

0.8487394957983193
0.65


In [8]:
print(lr.predict(test_scaled[10:20]))
print(test_target[10:20])

['Perch' 'Perch' 'Perch' 'Perch' 'Bream' 'Perch' 'Perch' 'Bream' 'Pike'
 'Bream']
['Roach' 'Perch' 'Perch' 'Perch' 'Bream' 'Perch' 'Perch' 'Bream' 'Pike'
 'Bream']


In [11]:
prob = lr.predict_proba(test_scaled[:5]).round(3)
print(prob.round(3))

[[0.011 0.118 0.531 0.012 0.22  0.086 0.023]
 [0.904 0.015 0.031 0.009 0.01  0.    0.031]
 [0.835 0.013 0.072 0.012 0.018 0.    0.05 ]
 [0.301 0.266 0.173 0.013 0.193 0.006 0.047]
 [0.192 0.004 0.48  0.182 0.036 0.    0.106]]


In [20]:
from sklearn.linear_model import SGDClassifier

sg = SGDClassifier(loss='log', max_iter=100)
sg.fit(train_scaled, train_target)

print(sg.score(train_scaled, train_target))
print(sg.score(test_scaled, test_target))

0.9159663865546218
0.775


In [21]:
sg.partial_fit(train_scaled, train_target)

print(sg.score(train_scaled, train_target))
print(sg.score(test_scaled, test_target))

0.8151260504201681
0.65
